### ISSUE TITLE
NoMethodError on Diffbot::Article

### ISSUE THREAD

**Issue by ProgrammingSam** [greshny/diffbot#11]
Hi, 

I'm currently trying to make your gem working. 

By following your documentation, I do : 

```
require 'diffbot'

Diffbot::Article.fetch(url, ENV['DIFFBOT_API']) do |request|
  request.html = true # Return HTML instead of plain text.
  request.summary = true # Return a summary text instead of the full text.
end
```

That returns : 

```
NoMethodError:
  The property 'nextPage' is not defined for Diffbot::Article.
```

Maybe the Diffbot API changed since issue #1 and its fix ?

Regards

**Comment by greshny** [comment]
hi @ProgrammingSam 
can you please send me any example URL to reproduce it?

Regards,
Roman

**Comment by ProgrammingSam** [comment]
Thank you for your quick answer ! 

But I found the problem myself...

In fact I'm crawling multiple urls by categories and it fails on some index pages like https://www.space.com/science-astronomy which I should avoid since they are not articles. 

I think that `Diffbot::Article.property :next_page, from: :nextPage` should be kept "just in case", I will try to find an example. 

Regards, 

Sami
