### ISSUE TITLE
Diffbot breaks when used with Hashie versions >= 3.0.0

### ISSUE THREAD

**Issue by saihgal** [greshny/diffbot#4]
``` ruby
    Diffbot::Article.fetch(@url,diffbot_token)
```

Above code works fine with Hashie versions till **2.1.2**. However refuses to play with Hashie version **3.0.0** onwards instead raising following error -

<pre>
/usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/trash.rb:80:in `property_exists?': The property 'tags' is not defined for this Trash. (NoMethodError)
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/trash.rb:49:in `[]='
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/diffbot-0.1.7/lib/diffbot/coercible_hash.rb:58:in `[]='
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/dash.rb:149:in `block in initialize_attributes'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/dash.rb:148:in `each_pair'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/dash.rb:148:in `initialize_attributes'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/trash.rb:96:in `initialize_attributes'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/hashie-3.0.0/lib/hashie/dash.rb:93:in `initialize'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/diffbot-0.1.7/lib/diffbot/article.rb:41:in `new'
    from /usr/local/rvm/gems/ruby-2.1.2@global/gems/diffbot-0.1.7/lib/diffbot/article.rb:41:in `fetch'
    from listbot.rb:9:in `initialize'
</pre>

**Comment by greshny** [comment]
Hi @nonocut

it's fixed a659780.

Thanks

**Comment by mihai-bobina** [comment]
Hi @greshny 

```
Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    diffbot (>= 0) ruby depends on
      nokogiri (~> 1.5.0) ruby

    rails (= 4.2.0) ruby depends on
      actionpack (= 4.2.0) ruby depends on
        rails-dom-testing (>= 1.0.5, ~> 1.0) ruby depends on
          nokogiri (1.6.0)
```

Any ideas how to fix this ?

**Comment by mihai-bobina** [comment]
```
