### ISSUE TITLE
Problem with Hashie 3.5

### ISSUE THREAD

**Issue by asabourin** [greshny/diffbot#7]
Hi there, we're not able to upgrade to Hashie 3.5.1 (which improves compatibility with Ruby 2.4) because of the following issue:
```
/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'diffbot'.
Gem Load Error is: uninitialized constant Hashie::Extensions::Coercion::RubyVersion
Did you mean?  RUBY_VERSION
```
Using Hashie 3.4.6 is fine though. Any idea how to fix the problem? Is the diffbot gem compatible with ruby 2.4? Thanks!

**Comment by greshny** [comment]
hi @asabourin 

Thanks for reporting!

please try version `0.1.14`.
